# Generated by Django 4.1 on 2022-09-22 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyWatchList',
            new_name='ItemWatchList',
        ),
    ]
