# Generated by Django 4.1 on 2022-09-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_rename_mywatchlist_itemwatchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemwatchlist',
            name='watched',
            field=models.CharField(max_length=255),
        ),
    ]
